// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnanNQ2EU5-lZ-opxP9iLYuofQ4cfxFE',
    appId: '1:737641305687:web:dfe574f1f261fd21df7512',
    messagingSenderId: '737641305687',
    projectId: 'basileapp-ead0d',
    authDomain: 'basileapp-ead0d.firebaseapp.com',
    storageBucket: 'basileapp-ead0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2Od3MXsWxOVn5sqyJ8mdEbFxE6YTCoo',
    appId: '1:737641305687:android:fd15604e2e5f3b88df7512',
    messagingSenderId: '737641305687',
    projectId: 'basileapp-ead0d',
    storageBucket: 'basileapp-ead0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUgdhTrTkDw2YnlyrqdA9pfeguG867D8',
    appId: '1:737641305687:ios:1aba3a32f5061ad6df7512',
    messagingSenderId: '737641305687',
    projectId: 'basileapp-ead0d',
    storageBucket: 'basileapp-ead0d.firebasestorage.app',
    iosBundleId: 'com.example.basileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuUgdhTrTkDw2YnlyrqdA9pfeguG867D8',
    appId: '1:737641305687:ios:1aba3a32f5061ad6df7512',
    messagingSenderId: '737641305687',
    projectId: 'basileapp-ead0d',
    storageBucket: 'basileapp-ead0d.firebasestorage.app',
    iosBundleId: 'com.example.basileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASnanNQ2EU5-lZ-opxP9iLYuofQ4cfxFE',
    appId: '1:737641305687:web:fb1be5725c1bc62edf7512',
    messagingSenderId: '737641305687',
    projectId: 'basileapp-ead0d',
    authDomain: 'basileapp-ead0d.firebaseapp.com',
    storageBucket: 'basileapp-ead0d.firebasestorage.app',
  );
}
